controllers:
    resource: ../src/Controller/
    type: attribute
# config/routes.yaml
dashboard:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index

kernel:
    resource: ../src/Kernel.php
    type: annotation
